# Generated by Django 2.2.3 on 2019-07-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('age', models.IntegerField()),
                ('gender', models.NullBooleanField()),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classses')),
            ],
        ),
        migrations.AddField(
            model_name='classses',
            name='m',
            field=models.ManyToManyField(to='app01.Teachers'),
        ),
    ]
