# Generated by Django 2.2.3 on 2019-07-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cs',
        ),
        migrations.DeleteModel(
            name='Classses',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
